### ISSUE TITLE
Better bootstrap usage

### ISSUE THREAD

**Issue by noplanman** [diasporg/Poduptime#102]
Would be cool to make better use of the bootstrap framework instead of custom fixes/hacks.

Namely, the sidebar and the menu items.

(I'll give it a go to also practice my designing a bit, but I'm no expert, just sayin'!)

**Comment by dmorley** [comment]
https://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/

I noticed they implimented this flex thing and changed layouts. Maybe you want to play with that? I wonder how long till beta on bs4
