### ISSUE TITLE
Ads...

### ISSUE THREAD

**Issue by noplanman** [diasporg/Poduptime#104]
I understand it's a source of revenue for you, but having ads on a page that promotes diaspora* (for what it is), it seems pretty weird to have Google Ads.

Personally I don't see them as they're blocked, it's a principle thing.

What are your thoughts on this?

**Comment by dmorley** [comment]
I have mixed feelings. Most people have ad blocker of course, including me so never see it. 
Let me think about it a bit, I have reduced server costs quite a bit and with Letsencrypt I hope to not have to spend on certs anymore so I could potentially loose the revenue and not be upside down. podupti.me has always paid a large chunk of diasp.org overall costs.

**Comment by noplanman** [comment]
Wow, that was quick!

I was also going to suggest to put a "Donate" or "Keep us going" or something button somewhere.

**Comment by dmorley** [comment]
I had one forever, never got used. Back when flattr was cool that got used. Will wait till the next cool thing comes around :)

**Comment by noplanman** [comment]
> Will wait till the next cool thing comes around :)

:smile:
