### ISSUE TITLE
Simplify SQL

### ISSUE THREAD

**Issue by noplanman** [diasporg/Poduptime#110]
As a next cleanup step, I'd like to sort out the SQL stuff and make it nice and clean.

I came across this library which could be good:
~https://github.com/shadowhand/latitude~
~**Edit:** https://github.com/doctrine/dbal~
**Edit2:** https://github.com/gabordemooij/redbean

@dmorley Take a look and let me know 👍

**Comment by dmorley** [comment]
Looks super nice and easy! Go for it.

**Comment by noplanman** [comment]
Have opted for [doctrine/dbal](https://github.com/doctrine/dbal) which also handles the DB and query execution etc.

Oh, and by the way, **no more `=== 't'`** 🎉

**Comment by noplanman** [comment]
Hmm, there's a lot of places where an SQL query that should return exactly 1 entry is handled as an array of multiple ones. This is the case when adding and editing the pod.

The pod domain should be unique, right?

**Comment by dmorley** [comment]
yes domain should be unique. Yes I did array when I should not have, I ran into some issue and took the easy route rather than figure it actually out.

**Comment by dmorley** [comment]
&doctrine looks cool, but also looks like greek

**Comment by noplanman** [comment]
@dmorley #118 uses [RedBean](http://redbeanphp.com/index.php).
