### ISSUE TITLE
Info I (&#8505;) not very universal

### ISSUE THREAD

**Issue by dmorley** [diasporg/Poduptime#111]
&#8505; seems unsupported everywhere.  FF on Win 7 shows as []. Chrome on Win7 shows right. FF on Android makes it a TINY i and Chrome on Android makes it a nice big i as intended. 

Something better should be used.

**Comment by noplanman** [comment]
What about the `:scroll:` 📜 ?
Or maybe the `:speech_balloon:` 💬 ?

**Comment by dmorley** [comment]
Here are some ones to try, lets see how they look on all devices
http://apps.timwhitlock.info/unicode/inspect?s=%F0%9F%93%9C%F0%9F%93%84%F0%9F%94%8D%F0%9F%92%AC%E2%84%B9

**Comment by dmorley** [comment]
http://emojipedia.org/speech-balloon/ looks the most compatible on Ubuntu, Windows, Samsung to me.

**Comment by noplanman** [comment]
@dmorley Ok 💬 it is then!
