### ISSUE TITLE
Score padding?

### ISSUE THREAD

**Issue by noplanman** [diasporg/Poduptime#114]
Regarding [this post](https://diasp.eu/posts/128d0ec0d96901345c400007cb0395aa) on diaspora*.

With every call of `pull.php`, the score goes up by 1 (which makes sense, as that's how it's coded).
But I'm just wondering if this needs some kind of overhaul or something, because if a pod does fall down in score, the `pull.php` can just be called 100 times and it's on 100 again (if there are no other issues reducing it).

**Comment by dmorley** [comment]
Yea it's very simple for sure and open to the world to hit. It also does not care if your pod is running year old bad code, it should. It could easily use total uptime and diff of code to have your top score more of a valid number not just did you pass 100 hours of checks to get to 100.

**Comment by noplanman** [comment]
Right. It just got me wondering what purpose the score has, if it can be "manipulated" so easily.

If a pod is up and running, latest software, tiny ping, it should just have a higher score.

I understand that downtime gets penalised, but I'm just scratching my head and wondering about the score and how to make it more meaningful.

**Comment by noplanman** [comment]
This is ok to close then, yes?

If we rethink this in the future, we'll reopen or just make a new issue.

**Comment by dmorley** [comment]
I think so yes, close
