### ISSUE TITLE
Remove outdated pods from the list

### ISSUE THREAD

**Issue by SuperTux88** [diasporg/Poduptime#130]
Can you please remove all pods older than 0.6.3.0 from the "Simple view" list (and the list used for random selection)? They aren't compatible anymore with the latest federation protocol. Especially diasp.ca, which is at the top, but has still 0.5.x ... so every user registering there is a lost user.

For long-term it would be cool to remove all pods that aren't updated in the last 6 month (4 minor releases), even when still compatible. But they are missing new features and probably security fixes, so it's nothing we should recommend for new users when the pod isn't well maintained.

**Comment by SuperTux88** [comment]
Can you please remove these outdated pods? Since the release of 0.7.0.0 more than 100 users registered on diasp.ca, they are now trapped on an outdated, unmaintained pod which isn't compatible with the network anymore. And that's only one pod, I didn't check the others. But diasp.ca is the biggest problem, because it is at the top of the list, has 100% uptime and has a lot of users, so it looks interesting, but it is the worst choice.

**Comment by dmorley** [comment]
A programmatic approach would be needed that represents all pods on all networks. Does nodeinfo offer some sort of compatible versions list? Or some way to tell the codebase what versions are compatible or not. How do diaspora nodes know to stop talking to these other nodes that are not compatible anymore?

**Comment by SuperTux88** [comment]
> A programmatic approach would be needed that represents all pods on all networks.

The easiest way is probably to only list the pods that are updated in the last 6 months. Because even if they are still compatible, a pod that wasn't updated for more than half a year is nothing I would recommend to new users (a lot of new stuff is missing and I don't know if the pod is updated in the future or if it stays unmaintained). Diaspora releases every 6 weeks, so that would be "only display the last 4 minor releases" (hotfix releases don't count here).

> How do diaspora nodes know to stop talking to these other nodes that are not compatible anymore?

They don't but the old pods just don't understand the new pods anymore. And even when it's not a 100% incompatible and they still understand the basics, older pods don't understand new stuff that was added since then.

So it is really important that podmins update their pods regularly (also because of security hotfixes).

**Comment by dmorley** [comment]
Only diaspora shows when the code was updated in the http headers so that would not work overall I think. So no easy way to know if someone is updating their code or not that I can think of?

I just had a thought. When did nodeinfo 2.0 come out? If I just change from checking 1.0 to 2.0 does that mostly solve this?

**Comment by SuperTux88** [comment]
NodeInfo 2.0 was added in 0.6.6.0, that would "disable" a lot more pods than needed (and I don't know if everybody else already implemented it).

If you can add the version to the ranking, so that the pod has a lower score the older the version is, that would already help a lot (so a pod with an old version can't stay at the top anymore).

An easier way than counting minor versions would be to just allow the current and the last major (0.6.0.0 is still 90% compatible to 0.7.0.0, but only 0.6.3.0 is fully compatible).

Or a bit better (but more complex): Only allow the current major and the last 4 minors of the last major (which would be 0.6.3.0 and newer). If the current major has at least 4 minors (so after 0.7.3.0 is released), remove last major from the list and only support the last 4 minors of the current major. That would allow people to have some time to do the major upgrade.

Because diaspora has scheduled releases and semver, it's easier here to create a rule to remove older pods from the list. I have no idea how to do that for other software.

**Comment by dmorley** [comment]
the other networks of course use different versioning and it;s all over the place. 

I think something simple if I look at it overall is the 2nd decimal space is > 1 then the code is pretty crusty, so that would eliminate sub 0.6.0.0 diaspora

**Comment by dmorley** [comment]
I also started to record the version number on each check on the last major release so at some point I will be able to chart updates, but that has not been long enough to use for this. At some point I can just check the DB for the last time their was a code update pod by pod.

**Comment by SuperTux88** [comment]
Yes,  that would only display the current and last major.

Another possibility would be to use the github releases API, and only display the last 4 releases for everybody, I think that should work for all software: https://api.github.com/repos/diaspora/diaspora/releases (I think that would be better than just allowing current and last major. But current and last major would already be better than nothing :) )

> At some point I can just check the DB for the last time their was a code update pod by pod.

The time isn't important, the version is important. If somebody updates now from 0.5.9.0 to 0.5.10.0 that wouldn't help at all. But when you record the versions yourself, you can check when you first saw a version (instead of using the github API) and then allow it for 6 month. (x.x.99.x versions are special, because they can last longer than 6 month)

Another possibility is to add a way how we (the core team) can manage versions, so we can maintain a list of versions that should be displayed in the main list (that way we can take care of compatible versions ourselves and also remove old versions earlier for example when there was a really important security hotfix)

**Comment by dmorley** [comment]
It's been 7 months since I opened this code base, going for a simple fix for now. I will look for long term solution when my head is back in this.

https://github.com/diasporg/Poduptime/pull/131
