### ISSUE TITLE
Cookie me

### ISSUE THREAD

**Issue by dmorley** [diasporg/Poduptime#149]
Maybe once you pick a pod we help you remember it via a cookie? 
I notice a lot of new users sign up and then do not remember the xxx.xxx domain of where they signed up. Maybe if we store that and know that at least we could suggest they go back there? 
Are cookies still bad? Or good?

**Comment by noplanman** [comment]
As we'd literally be using them "to improve the user experience", I think it would be totally fine.

The only question I have here, is how we know which pod the user registers on.
Say a user opens multiple pods directly from the list (which all go through `go.php`...), we won't be able to know which one the user chose in the end.
Same thing applies for the "Auto choose", which could be clicked but then the opened pod isn't the one the user wants to register on.

If we want to add this, we'd have to either save all the clicked links, or just the last one I guess :thinking: 
What do you think?

**Comment by dmorley** [comment]
I think the last. See my comment on dia.so also on other issue. Maybe that's a better place or moving that dia.so to podupti.me somehow. Or I am just making things more complex trying to wrap that into here!
