### ISSUE TITLE
Use podmin from nodeinfo

### ISSUE THREAD

**Issue by dmorley** [diasporg/Poduptime#154]
Nodeinfo tells us a pod contact name. Should we do something with that to help when people need to contact a podmin?

**Comment by noplanman** [comment]
I assume you mean the `metadata.adminAccount` field, right?

We could just add a direct link to that account if the metadata is available?

**Comment by dmorley** [comment]
Yea that one! Well in diasp.org case it would give you, https://diasp.org/u/welcome 
I think that's good if your on diasp.org but otherwise not so much. This reminds me of https://dia.so that I made so long ago, in this case it would jump you to https://dia.so/go/?welcome@diasp.org and if dia.so already had your cookie it would jump to your own pod and that contact. dia.so might also be a decent use case in https://github.com/diasporg/Poduptime/issues/145
Maybe we should think about wrapping dia.so into this project? I have not touched it in years.

**Comment by dmorley** [comment]
I was thinking maybe if !podminstatement then use metadata.adminAccount as podminstatement with a statement that is all we know

**Comment by noplanman** [comment]
Sounds good to me :+1:

**Comment by dmorley** [comment]
I still hesitate here. I feel like it's exposing more than people might expect. It also could expose email addresses to spam bots. I feel like this does not add much value, going to set aside for now
