### ISSUE TITLE
Let's get stricter with clean PHP7 and PSR-2

### ISSUE THREAD

**Issue by noplanman** [diasporg/Poduptime#156]
https://gophp71.org/ (We're on PHP7.2 already :tada:)

Basically, use `declare(strict_types=1);` for all PHP files and make sure that all PHP code is less flaky.

**Comment by dmorley** [comment]
I like it, what does PHP do if you =1 and then don't do it right? I find that PHP does not ever barf well and errors are usually vague, I assume this would be the same?

**Comment by noplanman** [comment]
As part of this issue, I'd like to introduce the PSR-2 style guide.
https://www.php-fig.org/psr/psr-2/

I saw that (since you're using PhpStorm?) you have some code bits that have 4 spaces as indentation, but most older code is 2.

Makes sense to have it clear all the way through, to make the code as pretty as can be :innocent:

**Comment by dmorley** [comment]
Ha, I thought the 2 spaces came from you :p no idea where that came into play now. Yea phpstorm defaults to 4 and I changed to 2 to comply to this project. I wonder if phpstorm has a fix all spacing button to make everything 4
