### ISSUE TITLE
Add a "cost" column

### ISSUE THREAD

**Issue by flashcode** [diasporg/Poduptime#157]
Hi,
It would be nice to have a "cost" column, indicating how much you have to pay to create an account on the pod.
Most are free, but some are not any more, for example diasp.eu now requires you to pay 11€ per year (see: https://diasp.eu/posts/7006572).
I think it would be a relevant info for users which are looking for a pod to know whether the subscription is free or not.

**Comment by dmorley** [comment]
I like the idea however this is not part of nodeinfo to pull from a pod, so for now I think it would just be a note the podmin could enter. Since $ is not in the base of diaspora I wonder if this would ever be in the nodeinfo updates.

**Comment by noplanman** [comment]
I think we can close off here and leave it up to podmins to add it to the comment field.
