### ISSUE TITLE
versions on pull-m and pull

### ISSUE THREAD

**Issue by dmorley** [diasporg/Poduptime#182]
develop branch still has issues. gango uses things like v0-alpha.46 masterversion and pod shows v3. Either we have to solve for all or we decide that we might include the normal versioning standards of the world and be ok with some pods just falling off the list if versions are going to be anything anyone picks for the day.

**Comment by noplanman** [comment]
Will figure something out.
Maybe @zauberstuhl is getting ready for a 0.1 soon? :innocent:

**Comment by Zauberstuhl** [comment]
@noplanman for sure ;)

@dmorley will change that to a semantic version asap `0.0.0-alpha.46` or something
sorry for the inconvenience :(

**Comment by dmorley** [comment]
thanks! maybe friendica can too :p ill have to ask em

**Comment by noplanman** [comment]
Maybe @annando and @tobiasd can chime in too?

**Comment by tobiasd** [comment]
I don't think that Friendica goes back to the old schema, as it does not reflect the way Friendica is developed and released. But 2018.05 can be read as major version 2018 minor version 05 if you need that schema. The DB version is probably not that important for your stats is it?

**Comment by dmorley** [comment]
That is workable thanks @tobiasd the jump from 3.6.0 to 2018-05 to 2018.08 was just hard to keep up with!

**Comment by tobiasd** [comment]
Yea, the dash was a glitch not intended. Sorry for that ;-) The format will stay year.month, with a -dev or -rc appended if appropriate.
