### ISSUE TITLE
Add TOS link

### ISSUE THREAD

**Issue by koehn** [diasporg/Poduptime#28]
It occurs to me that the main decision factors most people have when picking a pod are maintenance (uptime/upgrades), country of hosting, and TOS. If the software finds a TOS link, perhaps putting it prominently on the page would help. 

It would be nice if people could diff them, but that's probably asking a lot. 

See [here](https://diaspora.koehn.com/posts/358677) for more background.

**Comment by noplanman** [comment]
@dmorley We could add an extra field for this with the link to the terms page.

The default diaspora* one is `https://pod.url/terms`, so that could be the default input.

**Comment by dmorley** [comment]
@noplanman I added to the DB plan to add a text field for this, should be something the podmin can change from /terms to /myterms.html or whatever to support custom and other networks.

**Comment by noplanman** [comment]
Yes, that was what I thought too 👍 

The last thing to figure out is to find a nice place to put the link into the list and keeping it simple.

**Comment by dmorley** [comment]
https://github.com/diasporg/Poduptime/commit/454e55560f583a6e7a12fe2366b2dc9e6145e5e5
