### ISSUE TITLE
Could not validate your pod on http or https, check your setup!

### ISSUE THREAD

**Issue by raider444** [diasporg/Poduptime#31]
When I try to add my pod to list i receive message "Could not validate your pod on http or https, check your setup!"
pod.psynet.su is available by http and https. Certificate is valid.

**Comment by jhass** [comment]
You miss serving the intermediate certificate: https://www.sslshopper.com/ssl-checker.html#hostname=pod.psynet.su

**Comment by raider444** [comment]
Thanks, I've understood my problem. CA was appended to private key instead of certificate.
