### ISSUE TITLE
Add an option to check if Chat via XMPP is enabled

### ISSUE THREAD

**Issue by pavi** [diasporg/Poduptime#33]
I would like to see what pods are running with XMPP enabled. From  0.5.0.0 we have an experimental support. There are many new people who would be interested to just see chat running on Diaspora . Yes it has lot of vulnerabilities but there exists a usecase which can show all the nice features of Diaspora including chat. 
Pod uptime could have those stats and for a user a high up time pod with chat enabled is the best of both worlds .

**Comment by pavi** [comment]
I posted the issue at Diaspora core to expose the stats . https://github.com/diaspora/diaspora/issues/6211

**Comment by dmorley** [comment]
https://github.com/diasporg/Poduptime/commit/414e8eb2e552da5ae21b82cfdfd0f85dcec1822e
