### ISSUE TITLE
allow table sorting

### ISSUE THREAD

**Issue by keunes** [diasporg/Poduptime#34]
Would be great if it were possible to sort the advanced table (just like here: https://en.wikipedia.org/wiki/Help:Sorting#Example), so that viewers can easily determine themselves on which criteria they want to select a pod.

**Comment by dmorley** [comment]
This has always been a feature, are you talking about an improvement to it?

**Comment by keunes** [comment]
Well, actually, if i visit https://podupti.me/ and the table headings are normal text, no hyperlinks to sort the table and if I click on them, nothing happens. I don't see how I can sort the table, as it's supposed to be working there may be a bug, then? I'm using Firefox 40.0 on Ubuntu 14.04 LTS

**Comment by dmorley** [comment]
Ah never tried https on the site before, fixed the links to allow this to work now in http and https
