### ISSUE TITLE
Provide a way to change the domain

### ISSUE THREAD

**Issue by gabsoftware** [diasporg/Poduptime#37]
Hi, I'm the administrator of the pod freehuman.fr.

My pod changed domain from www.freehuman.fr to freehuman.fr, and since then, in podupti.me my pod appeared offline. I had to create a new key on uptimerobot and register the pod under the domain freehuman.fr.

So now there's a dupplicate for my pod.

Thus, it would be nice if we could edit the domain.

By the way you can delete the entry for www.freehuman.fr and if possible re-add the months to the entry for freehuman.fr.

**Comment by dmorley** [comment]
I think I am going to leave this as is. Really a pod with www and without are not the same since the encryption keys would not work and you would have to start over in the database or federation is dead for that pod. I think rare cleanup would be done on the backend where it makes sense.
