### ISSUE TITLE
Wrong country

### ISSUE THREAD

**Issue by tferreira** [diasporg/Poduptime#39]
Hi,

I have a pod hosted near Paris, France but Poduptime is displaying **GB**.

It looks like the database used by the PHP function geoip_record_by_name() was not accurate.
I directly contacted Maxmind to make them update their database, and now when I use this function on a PHP cli it returns the right country (FR).

Is there a way to make Poduptime update this value ?
I already tried using this:
https://podupti.me/db/pull.php?debug=1&domain=diaspora.psyco.fr

You may need to update the PHP geoip extension.

Thank you.

**Comment by dmorley** [comment]
Updated thanks for the reminder
