### ISSUE TITLE
Simplify database

### ISSUE THREAD

**Issue by noplanman** [diasporg/Poduptime#45]
At the moment, the database has many columns that should be altered.

**Wrong Types**
e.g. these should all just be boolean:
`hidden`, `ipv6` (string "yes" or "no")
`secure` (string "true" or "false")
`signup` (integer 1 or *null*)
`service_facebook` etc. (are boolean)

**Rename**
New column `xmpp` should be renamed to `service_xmpp` to follow the naming convention of the other services.
Integer columns that are summed up numbers should be named similarly (`total_*` vs. `*_count` vs. just a name like `local_posts`)

**Redundant Columns**
`connection`, `longversion`, `shortversion` and `masterversion` all have similar values.
This could be simplified to values that make perfect sense.
What's the difference between `shortversion` and `masterversion`? Some pods have totally different values here.

**Comment by dmorley** [comment]
Agree it makes sense to change the types and rename. 
shortversion=6.2.0 (basic version pulled from the pod)
longversion=6.2.0-head059840598 (I think no one cares, this could be dropped, it's not a human readable version)
masterversion=6.2.0 (this is taken from the github repo, what a up to date pod should be running based on if it is diaspora, or frendica etc), this should really be its own table of software versions and current revisions.

**Comment by dmorley** [comment]
also pingdom was the original provider for stats I used and they are no longer free so I do not think any pods are using their paid service. It would make sense to change the 'pingdomurl' and more to generic 'statsurl' etc. The Hxxx ones are also from before when pods did not have a json output and I scraped headers, can go away. 

What is the best way to clean this all up? In David land I would edit the tables.sql and the code that needs changing and then go and do the sql updates manually, however migration would make more sense of course. Ill poke around on the interwebs, but no idea what is cool these days, probably something.

Also /db/ folder should just be db items I think and all the php scripts should be in main dir? Who made this mess?

**Comment by noplanman** [comment]
I'd do it like you said. Instead of manually changing the DB structure, I'd write a script that does it for you. Especially as some things need special altering, like making all boolean fields also have boolean values. Not sure if just changing the type automatically does it right.

Also, having a script makes the deployment easier. Just update the new files and run the script, no downtime or weirdness.

**Comment by noplanman** [comment]
Just linking your gist here for easier access:
https://gist.github.com/dmorley/0a2470c91fcc5a6f583c67f51ba409f1

**Comment by dmorley** [comment]
I have updated my gist. I think it makes sense for me to create a branch and get to work on the changes, when it looks "feasable" to me I can push that branch up and we can iron things out before I even go a PR on it?

**Comment by noplanman** [comment]
Absolutely makes sense to start a branch for this!

Make a PR though, so that it's easier to comment and discuss the changes, instead of filling this issue with links 👍

**Comment by dmorley** [comment]
PR #66
