### ISSUE TITLE
"Auto pick a pod for you" incorrectly labeled

### ISSUE THREAD

**Issue by kewball** [diasporg/Poduptime#52]
"Auto pick" implies a reasoned process for determining an appropriate pod: language, location, popularity, etc. That is not the case.

Labeling the button "Random Pod" would be accurate.

**Comment by dmorley** [comment]
I was trying to avoid random as it might imply a pod that works at random and the code is trying to pick a good pod not just random, the script tries to do better than that. Maybe something like 
"Auto pick" the best pod for me based on uptime, and fresh code for me, explain what you get under the button or something?

**Comment by noplanman** [comment]
@kewball, check [here](https://github.com/diasporg/Poduptime/blob/bba9de24694b34f86532984ea09ac307deffe5c4/random.php#L7), it's not random at all 😃 
I agree with you @dmorley, "Auto pick" or "Choose a good pod for me" or something along those lines would make more sense.
