### ISSUE TITLE
table structure incomplete

### ISSUE THREAD

**Issue by dmorley** [diasporg/Poduptime#62]
I had to manually do a:
ALTER TABLE pods ADD masterversion text, ADD shortversion text, ADD longversion text;

since db/tables.sql did not add them for me.

**Comment by noplanman** [comment]
Might me a good time to redo the database with the changes from #45?

Having that out of the way will make further changes easier and won't require duplicate work.

**Comment by dmorley** [comment]
Yea, I was just pondering since those items are changes and these are somehow missing from the base tables.sql file for some reason. I was thinking if it might make sense to add them to the tables.sql file and then make them part of #45 if they are impacted. I just don't get how they are not in the sql file.

**Comment by noplanman** [comment]
> I just don't get how they are not in the sql file.

This is the export that you did from the live site, right?! Weird.

**Comment by dmorley** [comment]
No i loaded from db/tables.sql fresh. About to start a sqlmigration branch, 
I'll include these in the big group

**Comment by noplanman** [comment]
I suggest we move this over to #45 as not to have 2 similar discussions about the DB.
Ok?

**Comment by dmorley** [comment]
Yup
