### ISSUE TITLE
ratings popup seems inconsistant

### ISSUE THREAD

**Issue by dmorley** [diasporg/Poduptime#68]
https://podupti.me/rate.php?domain=Diasporing.ch gives no results
https://podupti.me/rate.php?domain=wk3.org gives results

they both have a ratings score so should both show results.

Seems hit and miss if they show results or not

**Comment by noplanman** [comment]
I think this has to do with the `admin` field, which is totally empty in some cases (so whether `1` or `0`)

Code is [here](https://github.com/diasporg/Poduptime/blob/f4fdf9b0b146959f4d033403f51bd4e398974776/rate.php#L70)

**Comment by noplanman** [comment]
Also part of this issue, the popup when clicking the link on the "Advanced" view is broken.

**Comment by dmorley** [comment]
I don't see it, which popup?

**Comment by noplanman** [comment]
Reproduce:
- Go to [Advanced View](https://podupti.me/?advancedview)
- Click on any link in the "Rating" column
- Get this:
![rating-popup-broken](https://cloud.githubusercontent.com/assets/9423417/21968366/3a61552a-db94-11e6-95eb-5a2a8db34c75.png)

**Comment by dmorley** [comment]
Is that a mac thing? looking on chrome and FF on Ubuntu and it does not do that.

**Comment by noplanman** [comment]
Weird, must be. I get it consistently on all browsers (FF, Opera, Chrome, Safari).

**Comment by dmorley** [comment]
what's your resolution? I'll try and reproduce somehow

**Comment by dmorley** [comment]
fixed this zindex
