### ISSUE TITLE
Missing other social networks

### ISSUE THREAD

**Issue by dmorley** [diasporg/Poduptime#85]
Frendica: https://github.com/friendica/friendica/blob/97020817225a8762b699a836da46ba6eed59a162/mod/statistics_json.php

Hubzilla: https://github.com/redmatrix/hubzilla/blob/56f66ce0011403dbec6f95a1dcbd81902f78af53/util/strings.php#L295

Currently external networks was evolved around diaspora, which supports a smaller set than most

**Comment by noplanman** [comment]
Is there a list somewhere that shows **all** supported networks that use nodeinfo?

**Comment by dmorley** [comment]
Not that I have seen. I wonder if it would make sense to just store the array rather than set values on the ones we know. Then we could display all the ones we have and show an icon for the ones we have icons for or something.

**Comment by dmorley** [comment]
This is in master now, new networks that pop up with nodeinfo will be autodiscovered and added to the list, the versions from github would be an easy hotfix when this happens
